services:

  mysql:
    image: mysql:8.0

    container_name: portfolio-mysql

    environment:
      MYSQL_ROOT_PASSWORD: ${PORTFOLIO_DB_PASSWORD}
      MYSQL_DATABASE: portfolio_db

    ports:
      - "3307:3306"

    volumes:
      - mysql-data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-uroot",
          "-p${PORTFOLIO_DB_PASSWORD}"
        ]
      interval: 10s
      timeout: 5s
      retries: 10


  portfolio-service:

    build:
      context: ./portfolio-service

    container_name: portfolio-service

    ports:
      - "${PORTFOLIO_SERVER_PORT}:8082"


    environment:

      # Database
      PORTFOLIO_DB_URL: ${PORTFOLIO_DB_URL}
      PORTFOLIO_DB_USERNAME: ${PORTFOLIO_DB_USERNAME}
      PORTFOLIO_DB_PASSWORD: ${PORTFOLIO_DB_PASSWORD}


      # JWT
      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_TOKEN_EXPIRATION: ${JWT_ACCESS_TOKEN_EXPIRATION}
      JWT_REFRESH_TOKEN_EXPIRATION: ${JWT_REFRESH_TOKEN_EXPIRATION}


      # Cloudinary
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}


      # Mail
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}


      # Owner email
      PORTFOLIO_OWNER_EMAIL: ${PORTFOLIO_OWNER_EMAIL}


    depends_on:
      mysql:
        condition: service_healthy


volumes:

  mysql-data: