# ===============================
# Application
# ===============================
spring.application.name=gateway-service
server.port=8080

# ===============================
# Eureka Configuration
# ===============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.main.web-application-type=reactive
# ===============================
# ===============================
# Gateway Discovery
# ===============================
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

# ===============================
# Gateway Routes
# ===============================
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/auth/**

spring.cloud.gateway.server.webflux.routes[1].id=portfolio-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://PORTFOLIO-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/profile/**

spring.cloud.gateway.server.webflux.routes[2].id=contact-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://CONTACT-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/v1/contact/**

spring.cloud.gateway.server.webflux.routes[3].id=media-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://MEDIA-SERVICE
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/v1/media/**

spring.cloud.gateway.server.webflux.routes[4].id=contact-service
spring.cloud.gateway.server.webflux.routes[4].uri=lb://contact-service
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/v1/contact/**

spring.cloud.gateway.server.webflux.routes[5].id=email-service
spring.cloud.gateway.server.webflux.routes[5].uri=lb://email-service
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/v1/email/**

# JWT Configuration
jwt.secret=VGhpc0lzQVN1cGVyU2VjcmV0S2V5Rm9ySldUU2lnbmluZ0FuZEl0TXVzdEJlTG9uZ0Vub3VnaA==
jwt.access-token-expiration=900000
# ===============================
# Logging
# ===============================
logging.level.org.springframework.cloud.gateway=INFO
logging.level.org.springframework.web=INFO