# ===============================
# SERVER CONFIG
# ===============================

server.port=8083


# ===============================
# APPLICATION NAME
# ===============================

spring.application.name=MEDIA-SERVICE

springdoc.swagger-ui.path=/swagger-ui.html

# ===============================
# EUREKA CONFIG
# ===============================

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

eureka.instance.prefer-ip-address=true



# ===============================
# CLOUDINARY CONFIG
# ===============================

#cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}

#cloudinary.api-key=${CLOUDINARY_API_KEY}

#cloudinary.api-secret=${CLOUDINARY_API_SECRET}

cloudinary.cloud-name=t4o2vhpa
cloudinary.api-key=897565828952728
cloudinary.api-secret=tr3F8o8bu2VMlYqdEs6ERoAtvlk



# ===============================
# MULTIPART CONFIG
# ===============================

spring.servlet.multipart.enabled=true

spring.servlet.multipart.max-file-size=10MB

spring.servlet.multipart.max-request-size=10MB



# ===============================
# ACTUATOR
# ===============================

management.endpoints.web.exposure.include=health,info

management.endpoint.health.show-details=always