# ===============================
# SERVER CONFIG
# ===============================

server.port=${MEDIA_SERVER_PORT:8083}

# ===============================
# APPLICATION NAME
# ===============================

spring.application.name=MEDIA-SERVICE

springdoc.swagger-ui.path=/swagger-ui.html

# ===============================
# EUREKA CONFIG
# ===============================

eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka}

eureka.instance.prefer-ip-address=true

#eureka.instance.hostname=localhost

# ===============================
# CLOUDINARY CONFIG
# ===============================

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:t4o2vhpa}
cloudinary.api-key=${CLOUDINARY_API_KEY:897565828952728}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:tr3F8o8bu2VMlYqdEs6ERoAtvlk}

# ===============================
# MULTIPART CONFIG
# ===============================

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# ===============================
# ACTUATOR
# ===============================

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always