# ===============================
# Application
# ===============================
spring.application.name=contact-service

server.port=${CONTACT_SERVER_PORT:8084}

springdoc.swagger-ui.path=/swagger-ui.html

# ===============================
# Portfolio
# ===============================
portfolio.owner.email=${PORTFOLIO_OWNER_EMAIL:9upendrad@gmail.com}

# ===============================
# MySQL
# ===============================
spring.datasource.url=${CONTACT_DB_URL:jdbc:mysql://localhost:3306/contact_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC}
spring.datasource.username=${CONTACT_DB_USERNAME:root}
spring.datasource.password=${CONTACT_DB_PASSWORD:root}

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Eureka
# ===============================
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka}


eureka.instance.prefer-ip-address=true
#eureka.instance.hostname=localhost
# ===============================
# Actuator
# ===============================
management.endpoints.web.exposure.include=health,info