spring.application.name=portfolio-service

server.port=8082

spring.datasource.url=${PORTFOLIO_DB_URL:jdbc:mysql://localhost:3306/portfolio_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC}

spring.datasource.username=${PORTFOLIO_DB_USERNAME:root}
spring.datasource.password=${PORTFOLIO_DB_PASSWORD:root}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

jwt.secret=${JWT_SECRET:VGhpc0lzQVN1cGVyU2VjcmV0S2V5Rm9ySldUU2lnbmluZ0FuZEl0TXVzdEJlTG9uZ0Vub3VnaA==}

jwt.access-token-expiration=${JWT_ACCESS_TOKEN_EXPIRATION:90000000}

jwt.refresh-token-expiration=${JWT_REFRESH_TOKEN_EXPIRATION:604800000}



# Mail
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:upendrasri9@gmail.com}
spring.mail.password=${MAIL_PASSWORD:yucscjihjiqwcdaj}




spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:t4o2vhpa}
cloudinary.api-key=${CLOUDINARY_API_KEY:897565828952728}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:tr3F8o8bu2VMlYqdEs6ERoAtvlk}



# Multipart
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Portfolio
portfolio.owner.email=${PORTFOLIO_OWNER_EMAIL:upendrasri9@gmail.com}

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

